version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  prepare:
    executor:
      name: get code
    steps:
      - checkout
  build-and-test:
    executor:
      name: node/default
      working_directory: exercise-cal-app
    steps:
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - prepare
        - build-and-test
